AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack for BusBeacon - Creates CloudFront distribution

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${!ImportValue WebsiteBucketName}.s3-website-${AWS::Region}.amazonaws.com
            Id: S3Origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              HTTPSPort: 443
              OriginSSLProtocols:
                - TLSv1.2
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  WebsiteUrl:
    Description: URL to access the BusBeacon website
    Value: !Sub https://${CloudFrontDistribution.DomainName}
  ApiGatewayUrl:
    Description: API Gateway URL for the backend
    Value: !ImportValue ApiGatewayUrl